version: "3"

services:
  api:
    build: .
    ports:
      - "7000:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      JWT_SECRET: mojsuperjakijwtsecret
      TOKEN_DURATION: 15m
      REFRESH_TOKEN_DURATION: 168h
      DB_DRIVER: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: go_api
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: go_api
    ports:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
